name: Get package version
inputs:
  file:
    description: path to package.json
    required: false
    default: package.json
outputs:
  version:
    description: version retrieved from ${{ inputs.file }}
    value: ${{ steps.get.outputs.value }}
runs:
  using: composite
  steps:
  - id: get
    name: Get package version from ${{ inputs.file }}
    shell: bash
    run: |-
      node-package-version get ${{ inputs.file }}
      echo "value=$(node-package-version get ${{ inputs.file }})" >> $GITHUB_OUTPUT
