name: Compare package version
inputs:
  file:
    description: path to package.json
    required: false
    default: package.json
  version:
    description: version in SemVer format
    required: true
  regex:
    description: ECMAScript Regular Expression to parse the version string for verification
    required: false
    default: "^(?<major>0|[1-9]\\d*)\\.(?<minor>0|[1-9]\\d*)(\\.(?<patch>0|[1-9]\\d*))?(?:-(?<prerelease>(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+(?<buildmetadata>[0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
outputs:
  result:
    description: Result of comparison, -1 -> given version is small than package version, 1 -> greater, 0 -> equal
    value: ${{ steps.cmp.outputs.value }}
runs:
  using: composite
  steps:
  - id: cmp
    name: Compare package version '${{ inputs.version }}' to ${{ inputs.file }}
    shell: bash
    run: |-
      node-package-version cmp --version '${{ inputs.version}}' --regex '${{ inputs.regex }}' '${{ inputs.file }}'
      echo "value=$(node-package-version cmp --version '${{ inputs.version}}' --regex '${{ inputs.regex }}' '${{ inputs.file }}')" >> $GITHUB_OUTPUT
