name: Test Bump

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Bump
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: npm install

      # basic simple test: just bump this package's version
      - name: Test functionality
        run: |
          node . bump  --major --minor --patch    package.json
          echo "version=$(node . get    package.json)" >> $GITHUB_OUTPUT
        id: test
      - name: Print results
        run: echo ${{ steps.test.outputs.version }}

      # simple test on fixed test data
      - name: Test patch on simple format
        run: |
          node . bump  --patch    testdata/simple/package.json
          echo "version=$(node . get    testdata/simple/package.json)" >> $GITHUB_OUTPUT
        id: simple_patch
      - name: Print results
        run: echo ${{ steps.simple_patch.outputs.version }}
      - name: Verify results
        run: |
          if [ "${{ steps.simple_patch.outputs.version }}" == "1.2.4" ]; then
            echo "Version matches"
          else
            echo "Version mismatch"
            exit -1
          fi

      - name: Test minor on simple format
        run: |
          node . bump  --minor    testdata/simple/package.json
          echo "version=$(node . get    testdata/simple/package.json)" >> $GITHUB_OUTPUT
        id: simple_minor
      - name: Print results
        run: echo ${{ steps.simple_minor.outputs.version }}
      - name: Verify results
        run: |
          if [ "${{ steps.simple_minor.outputs.version }}" == "1.3.4" ]; then
            echo "Version matches"
          else
            echo "Version mismatch"
            exit -1
          fi

      - name: Test major on simple format
        run: |
          node . bump  --major    testdata/simple/package.json
          echo "version=$(node . get    testdata/simple/package.json)" >> $GITHUB_OUTPUT
        id: simple_major
      - name: Print results
        run: echo ${{ steps.simple_major.outputs.version }}
      - name: Verify results
        run: |
          if [ "${{ steps.simple_major.outputs.version }}" == "2.3.4" ]; then
            echo "Version matches"
          else
            echo "Version mismatch"
            exit -1
          fi

      # simple test with custom regex on fixed test data
      - name: Test on simple format with custom regex
        run: |
          node . bump  --regex '^(?<major>[0-9]+)\.(?<minor>[0-9]+)\.(?<patch>[0-9]+)$' --major --minor --patch   testdata/simple/package.json
          echo "version=$(node . get    testdata/simple/package.json)" >> $GITHUB_OUTPUT
        id: custom
      - name: Print results
        run: echo ${{ steps.custom.outputs.version }}
      - name: Verify results
        run: |
          if [ "${{ steps.custom.outputs.version }}" == "3.4.5" ]; then
            echo "Version matches"
          else
            echo "Version mismatch"
            exit -1
          fi

      # prerelease test on fixed test data
      - name: Test on prerelease format
        run: |
          node . bump  --major --minor --patch    testdata/prerelease/package.json
          echo "version=$(node . get    testdata/prerelease/package.json)" >> $GITHUB_OUTPUT
        id: prerelease
      - name: Print results
        run: echo ${{ steps.prerelease.outputs.version }}
      - name: Verify results
        run: |
          if [ "${{ steps.prerelease.outputs.version }}" == "2.3.4-beta.5" ]; then
            echo "Version matches"
          else
            echo "Version mismatch"
            exit -1
          fi

      # buildmeta test on fixed test data
      - name: Test on buildmetadata format
        run: |
          node . bump  --major --minor --patch    testdata/buildmeta/package.json
          echo "version=$(node . get    testdata/buildmeta/package.json)" >> $GITHUB_OUTPUT
        id: buildmeta
      - name: Print results
        run: echo ${{ steps.buildmeta.outputs.version }}
      - name: Verify results
        run: |
          if [ "${{ steps.buildmeta.outputs.version }}" == "2.3.4+foobar.42" ]; then
            echo "Version matches"
          else
            echo "Version mismatch"
            exit -1
          fi

      # complex test on fixed test data
      - name: Test on complex format
        run: |
          node . bump  --major --minor --patch    testdata/complex/package.json
          echo "version=$(node . get    testdata/complex/package.json)" >> $GITHUB_OUTPUT
        id: complex
      - name: Print results
        run: echo ${{ steps.complex.outputs.version }}
      - name: Verify results
        run: |
          if [ "${{ steps.complex.outputs.version }}" == "2.3.4-beta.5+foobar.42" ]; then
            echo "Version matches"
          else
            echo "Version mismatch"
            exit -1
          fi
